services:
  web:
    container_name: 'senoragarabato'
    build: .
    command: bundle exec rails s -b '0.0.0.0'
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=production
    env_file: ".env"
    networks:
      - main
    volumes:
      - app-storage:/rails/storage

  demo_web:
    container_name: 'demo_senoragarabato'
    build: .
    command: bundle exec rails s -b '0.0.0.0'
    ports:
      - "3001:3001"
    environment:
      - RAILS_ENV=development
      - RAILS_SERVE_STATIC_FILES=false
      - RAILS_LOG_TO_STDOUT=true
    env_file: ".env"
    networks:
      - main
    volumes:
      - demo-storage:/rails/storage

volumes:
  app-storage: {}
  demo-storage: {} 

networks:
  main:
    external: true
    driver: bridge
