services:
  web:
    container_name: 'senoragarabato'
    build: .
    command: bundle exec rails s -b '0.0.0.0'  # Usar el comando aquí
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=test
    env_file: ".env"
    develop:
      watch:
        - action: rebuild
          path: .
    networks:
      - main

  demo_web:
    build: .
    command: "./bin/rails server"
    env_file:
      - ./.env
    volumes:
      - app-storage:/rails/storage
    networks:
      - main

volumes:
  app-storage: {}

networks:
  main:
    external: true
    driver: bridge
