test:
  # Credentials for REST APIs
  client_id: <%= Rails.application.credentials.paypal_client_id %>
  client_secret: <%= Rails.application.credentials.paypal_secret %>
  # Mode can be 'live' or 'sandbox'
  mode: sandbox

development:
  client_id: <%= Rails.application.credentials.paypal_client_id %>
  client_secret: <%= Rails.application.credentials.paypal_secret %>
  mode: sandbox

production:
  client_id: <%= Rails.application.credentials.paypal_client_id %>
  client_secret: <%= Rails.application.credentials.paypal_secret %>
  mode: live

